export interface MediaItem {
  id: string;
  title: string;
  year: number;
  type: "Movie" | "TV Series" | "Documentary" | "Anime";
  rating: number;
  genres: string[];
  description: string;
  posterGradient: string;
  posterImage?: string;
  runtime?: string;
  seasons?: number;
}

export const heroMedia: MediaItem = {
  id: "hero-1",
  title: "Beyond the Horizon",
  year: 2025,
  type: "Movie",
  rating: 9.2,
  genres: ["Sci-Fi", "Adventure", "Drama"],
  description:
    "A lone astronaut discovers a gateway to parallel universes on the edge of a dying planet. As reality fractures around them, they must choose between saving one world or losing themselves across infinite dimensions.",
  posterGradient: "from-purple-900 via-blue-900 to-slate-900",
  posterImage: "/streamex/hero-poster.png",
  runtime: "2h 28m",
};

export const trendingNow: MediaItem[] = [
  {
    id: "t-1",
    title: "The Last Algorithm",
    year: 2025,
    type: "TV Series",
    rating: 8.8,
    genres: ["Thriller", "Sci-Fi"],
    description: "An AI researcher uncovers a conspiracy.",
    posterGradient: "from-cyan-800 via-blue-900 to-slate-900",
    seasons: 2,
  },
  {
    id: "t-2",
    title: "Crimson Peak",
    year: 2024,
    type: "Movie",
    rating: 7.9,
    genres: ["Horror", "Mystery"],
    description: "A gothic horror tale of love and deceit.",
    posterGradient: "from-red-900 via-rose-900 to-slate-900",
    runtime: "1h 54m",
  },
  {
    id: "t-3",
    title: "Street Legends",
    year: 2025,
    type: "Movie",
    rating: 8.4,
    genres: ["Action", "Crime"],
    description: "Underground racing with deadly stakes.",
    posterGradient: "from-amber-800 via-orange-900 to-slate-900",
    runtime: "2h 12m",
  },
  {
    id: "t-4",
    title: "Echoes of Tomorrow",
    year: 2024,
    type: "TV Series",
    rating: 9.1,
    genres: ["Drama", "Sci-Fi"],
    description: "Time loops create intertwined fates.",
    posterGradient: "from-emerald-800 via-teal-900 to-slate-900",
    seasons: 3,
  },
  {
    id: "t-5",
    title: "The Grand Illusion",
    year: 2025,
    type: "Movie",
    rating: 8.7,
    genres: ["Drama", "Mystery"],
    description: "A magician's tricks hide dark secrets.",
    posterGradient: "from-violet-800 via-purple-900 to-slate-900",
    runtime: "2h 05m",
  },
  {
    id: "t-6",
    title: "Arctic Fury",
    year: 2024,
    type: "Movie",
    rating: 7.6,
    genres: ["Action", "Thriller"],
    description: "Survival against nature and enemies.",
    posterGradient: "from-sky-800 via-cyan-900 to-slate-900",
    runtime: "1h 58m",
  },
  {
    id: "t-7",
    title: "Digital Hearts",
    year: 2025,
    type: "Anime",
    rating: 8.9,
    genres: ["Romance", "Sci-Fi"],
    description: "Love blooms in a virtual reality world.",
    posterGradient: "from-pink-800 via-fuchsia-900 to-slate-900",
    seasons: 1,
  },
  {
    id: "t-8",
    title: "Shadow Protocol",
    year: 2024,
    type: "TV Series",
    rating: 8.3,
    genres: ["Action", "Spy"],
    description: "Covert operations with global consequences.",
    posterGradient: "from-gray-700 via-zinc-800 to-slate-900",
    seasons: 2,
  },
  {
    id: "t-9",
    title: "The Silent Garden",
    year: 2025,
    type: "Movie",
    rating: 8.5,
    genres: ["Drama", "Fantasy"],
    description: "A mystical garden grants forgotten memories.",
    posterGradient: "from-lime-800 via-green-900 to-slate-900",
    runtime: "1h 48m",
  },
  {
    id: "t-10",
    title: "Neon Requiem",
    year: 2024,
    type: "Movie",
    rating: 8.1,
    genres: ["Cyberpunk", "Action"],
    description: "A hacker fights corporate overlords in Neo-Tokyo.",
    posterGradient: "from-fuchsia-800 via-pink-900 to-slate-900",
    runtime: "2h 15m",
  },
];

export const topRated: MediaItem[] = [
  {
    id: "tr-1",
    title: "The Godfather: Legacy",
    year: 2024,
    type: "Movie",
    rating: 9.4,
    genres: ["Crime", "Drama"],
    description: "The definitive crime saga continues.",
    posterGradient: "from-amber-900 via-yellow-900 to-stone-900",
    runtime: "2h 45m",
  },
  {
    id: "tr-2",
    title: "Wanderers",
    year: 2023,
    type: "TV Series",
    rating: 9.3,
    genres: ["Drama", "Adventure"],
    description: "A group travels across post-apocalyptic landscapes.",
    posterGradient: "from-orange-800 via-amber-900 to-stone-900",
    seasons: 4,
  },
  {
    id: "tr-3",
    title: "The Mathematician",
    year: 2025,
    type: "Movie",
    rating: 9.0,
    genres: ["Biography", "Drama"],
    description: "The untold story of a mathematical genius.",
    posterGradient: "from-indigo-800 via-blue-900 to-stone-900",
    runtime: "2h 20m",
  },
  {
    id: "tr-4",
    title: "Phantom Waltz",
    year: 2024,
    type: "Movie",
    rating: 8.9,
    genres: ["Music", "Drama"],
    description: "A pianist hears music from the beyond.",
    posterGradient: "from-slate-700 via-gray-800 to-neutral-900",
    runtime: "1h 55m",
  },
  {
    id: "tr-5",
    title: "Desert Bloom",
    year: 2023,
    type: "Movie",
    rating: 8.8,
    genres: ["Romance", "Drama"],
    description: "Love story set against Saharan backdrop.",
    posterGradient: "from-yellow-800 via-orange-900 to-stone-900",
    runtime: "2h 02m",
  },
  {
    id: "tr-6",
    title: "Code Zero",
    year: 2025,
    type: "TV Series",
    rating: 9.1,
    genres: ["Thriller", "Tech"],
    description: "A zero-day exploit threatens global systems.",
    posterGradient: "from-green-800 via-emerald-900 to-stone-900",
    seasons: 1,
  },
  {
    id: "tr-7",
    title: "The Painter",
    year: 2024,
    type: "Movie",
    rating: 8.7,
    genres: ["Art", "Biography"],
    description: "A tortured artist's final masterpiece.",
    posterGradient: "from-rose-800 via-red-900 to-stone-900",
    runtime: "2h 10m",
  },
  {
    id: "tr-8",
    title: "Abyssal",
    year: 2025,
    type: "Movie",
    rating: 8.6,
    genres: ["Horror", "Sci-Fi"],
    description: "Deep sea creatures emerge from the trench.",
    posterGradient: "from-blue-900 via-slate-900 to-black",
    runtime: "1h 52m",
  },
  {
    id: "tr-9",
    title: "Sakura Dreams",
    year: 2024,
    type: "Anime",
    rating: 9.2,
    genres: ["Slice of Life", "Fantasy"],
    description: "A girl's magical journey through ancient Japan.",
    posterGradient: "from-pink-700 via-rose-800 to-stone-900",
    seasons: 2,
  },
  {
    id: "tr-10",
    title: "Iron Resolve",
    year: 2023,
    type: "Movie",
    rating: 8.5,
    genres: ["War", "Drama"],
    description: "WWII soldiers face impossible odds.",
    posterGradient: "from-stone-700 via-zinc-800 to-neutral-900",
    runtime: "2h 35m",
  },
];

export const newReleases: MediaItem[] = [
  {
    id: "nr-1",
    title: "Velocity",
    year: 2025,
    type: "Movie",
    rating: 8.2,
    genres: ["Action", "Sci-Fi"],
    description: "Speed is the only way out.",
    posterGradient: "from-red-700 via-orange-800 to-slate-900",
    runtime: "2h 01m",
  },
  {
    id: "nr-2",
    title: "The Arrangement",
    year: 2025,
    type: "TV Series",
    rating: 7.8,
    genres: ["Comedy", "Romance"],
    description: "An arranged marriage turns unconventional.",
    posterGradient: "from-teal-700 via-cyan-800 to-slate-900",
    seasons: 1,
  },
  {
    id: "nr-3",
    title: "Deep State",
    year: 2025,
    type: "Movie",
    rating: 8.5,
    genres: ["Political", "Thriller"],
    description: "A journalist uncovers government secrets.",
    posterGradient: "from-slate-600 via-gray-700 to-neutral-800",
    runtime: "2h 18m",
  },
  {
    id: "nr-4",
    title: "Galactic Drift",
    year: 2025,
    type: "Anime",
    rating: 8.7,
    genres: ["Space", "Adventure"],
    description: "Space pirates search for a legendary planet.",
    posterGradient: "from-violet-700 via-purple-800 to-slate-900",
    seasons: 1,
  },
  {
    id: "nr-5",
    title: "The Witness",
    year: 2025,
    type: "Movie",
    rating: 8.0,
    genres: ["Crime", "Legal"],
    description: "A key witness becomes the prime suspect.",
    posterGradient: "from-amber-700 via-yellow-800 to-slate-900",
    runtime: "1h 59m",
  },
  {
    id: "nr-6",
    title: "Frozen Tides",
    year: 2025,
    type: "Movie",
    rating: 7.5,
    genres: ["Disaster", "Drama"],
    description: "A tsunami hits during a record freeze.",
    posterGradient: "from-sky-700 via-blue-800 to-slate-900",
    runtime: "2h 08m",
  },
  {
    id: "nr-7",
    title: "Circuit Breaker",
    year: 2025,
    type: "TV Series",
    rating: 8.3,
    genres: ["Tech", "Thriller"],
    description: "The internet goes dark worldwide.",
    posterGradient: "from-emerald-700 via-green-800 to-slate-900",
    seasons: 1,
  },
  {
    id: "nr-8",
    title: "Whispers in the Dark",
    year: 2025,
    type: "Movie",
    rating: 7.9,
    genres: ["Horror", "Psychological"],
    description: "A therapist's patients share the same nightmare.",
    posterGradient: "from-zinc-700 via-neutral-800 to-stone-900",
    runtime: "1h 47m",
  },
  {
    id: "nr-9",
    title: "Last Light",
    year: 2025,
    type: "Movie",
    rating: 8.6,
    genres: ["Sci-Fi", "Drama"],
    description: "Humanity's final sunset approaches.",
    posterGradient: "from-orange-700 via-red-800 to-slate-900",
    runtime: "2h 22m",
  },
  {
    id: "nr-10",
    title: "The Heist",
    year: 2025,
    type: "Movie",
    rating: 8.1,
    genres: ["Heist", "Action"],
    description: "The most elaborate robbery ever conceived.",
    posterGradient: "from-yellow-700 via-amber-800 to-slate-900",
    runtime: "2h 14m",
  },
];

export const allMedia: MediaItem[] = [
  heroMedia,
  ...trendingNow,
  ...topRated,
  ...newReleases,
];

export function searchMedia(query: string): MediaItem[] {
  const lower = query.toLowerCase();
  return allMedia.filter(
    (item) =>
      item.title.toLowerCase().includes(lower) ||
      item.genres.some((g) => g.toLowerCase().includes(lower)) ||
      item.type.toLowerCase().includes(lower) ||
      item.description.toLowerCase().includes(lower)
  );
}
